version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/:/go/app
    tty: true
    env_file: ./app/.env
    depends_on:
      - mysql
  mysql:
    container_name: go_mysql_db
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    image: mysql:8.0
    platform: linux/x86_64
    restart: always
    environment:
      MYSQL_DATABASE: mysqldb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - data-store-mysql:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/log:/var/log/mysql
    ports:
      - "3306:3306"
  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
      
volumes: 
  data-store-mysql:

      